### ISSUE TITLE
VM's are not accessible.

### ISSUE THREAD

**Issue by bardia13** [masjohncook/CREMEv2#33]
Hi
I am trying to use this tool to create an attack dataset for my research. Unfortunately, all the VMs other than the controller is not available to download. Is it possible for you to make them public? 

Thanks

**Comment by masjohncook** [comment]
Hi Bardia13, 

We apologize for the inconvenience. We already update the VM link. 

If you have any issues with it don't hesitate to contact us. 

Thank you
